<a href="https://colab.research.google.com/github/Emheria-underline/HelloWorld/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tenses
Pytorch tensor are created using 'torch.Tensor()' -= https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([7, 8])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
ttr = torch.tensor([[[1,5,7],
                     [6, 8, 1]]
                              ,[[1, 4, 6],
                              [2, 3, 6]]])
ttr[1,0,2]

tensor(6)

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
why random Tensor?

random Tensors are importet because the way many neural networks learn is taht they start with tensor full of random numbers then adjust those random numbers to better represent teh data.

Start with random numbers-> look at datat -> update random numbers-> look at data update random numbers
Torch random tensor - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.randn(3, 4)
random_tensor

tensor([[ 0.5419, -0.4661,  0.1849, -1.1628],
        [-0.2201,  2.2878,  1.1774,  0.8190],
        [-0.0315, -0.7306,  0.4849,  0.8271]])

In [ ]:
#Create a random tensor wiht similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor.dtype

torch.float32

### Creating a a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get depraceated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

** Note:** Tensor datatypees is one of the big 3 errors youll run into with pytorch learning:
1. Tensor not right dataytype
2. Tensor not right shape
3. Tensor not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g 16 32)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whetever or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensor (tensor attribute)

1.Tensor not right dataytype - to do get datatype from a tensor, can use "tensor.dtype"

2.Tensor not right shape - to get shape from a tensor, can use "tensor.shape"

3.Tensor not on the right device - to get device from a tensor, can use tensor.device

In [ ]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6304, 0.1520, 0.6681, 0.5260],
        [0.3182, 0.3436, 0.7484, 0.1231],
        [0.1459, 0.3748, 0.2081, 0.5581]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6304, 0.1520, 0.6681, 0.5260],
        [0.3182, 0.3436, 0.7484, 0.1231],
        [0.1459, 0.3748, 0.2081, 0.5581]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
 * addition
 * subtraktion
 * Multiplikation (element-wise)
 * Division
 * Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multitplay a tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Elemnt-wise multiplication
2. Matrix-Multiplication (dot product)

There are two main rules that performing matrix mulitplication needs to satisfy:
1. The **inner dimension must match**:
* (3, 2) @ (3, 2) this wont work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the **outer dimenion**:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 509 µs, sys: 0 ns, total: 509 µs
Wall time: 1.94 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 68 µs, sys: 0 ns, total: 68 µs
Wall time: 71.3 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it`s an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one our tensor using torch.transpose

A **transpose schwitches the axxes or dimensions or given a tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B , tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
Output = torch.matmul(tensor_A, tensor_B.T)
print(Output)
print(f"\nOutput shape: {Output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
# Find the min/smalles
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(dtype=torch.float32)), x.type(dtype=torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tesnor that has the minimum value wiht argmin () -> returns index position of target tensor where the minimum value occurs

x.argmin()

tensor(0)

In [ ]:
x[0]

In [ ]:
# Find the postion in tensor that has the maximum value with argmax()
x.argmax()

In [ ]:
x[9]

## Reshaping, stacking, squeezing and unsqueezing tensors

*Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 'l' dimensions from a tensor
* Unsqueeze - add a 'l' dimension to a target tensor
* Permute - Return a view of the input with a dimension permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squezze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor {x_unsqueezed}")
print(f"New shape {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimension of a target tensor in a specifed order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour, height width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 722
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(722.), tensor(722.))

## Indexing (selecting data from a tensors)

Indexing with Pytorch is similar with Numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10). reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 dimension but only 1 index value of 1st and 2nd dimenion
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th dimension and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## Pytorch tensor & NumPy

Numpy is a polpular scientific python numerical computing library#

And because of this, Pyytorsch has functionaltity to interact with it.

* Data in NumPy, want Pytorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.tensor.numpy()

In [ ]:
# Numpy arrange to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning when converting form numpy -> pytorch reflects numpys default datatype of float 64 unless specifed otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Change the value of array, what will this do to 'tensor'
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> agian -> agian...

To reduve the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create random tensores
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)

tensor([[0.2354, 0.3715, 0.0156, 0.7067],
        [0.9934, 0.5659, 0.1086, 0.4197],
        [0.4193, 0.6858, 0.1999, 0.7330]])
tensor([[0.0570, 0.3554, 0.0195, 0.7492],
        [0.7019, 0.2223, 0.1223, 0.9010],
        [0.7607, 0.7648, 0.7430, 0.7047]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Lets make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3 ,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra infos of Reproducibility: https://docs.pytorch.org/docs/stable/notes/randomness.html

## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDa + NVIDIa hardware + Pytorch working behind the scenes

### 1. Getting a GPU
1. Easiest - use google colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requies the invesment of buying a gpu
3. Use cloud computing - CGP, AWS, Azure, these services allow you to rent computers on the cloud

https://github.com/mrdbourke/pytorch-deep-learning

### 2. Check for GPU acces with Pytorch

In [ ]:
# Check for Gpu acces with Pytorch
import torch

torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models because using a GPU results in faster computation

In [ ]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU


In [ ]:
# If tensor is on GPU, cant transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

NameError: name 'tensor_on_gpu' is not defined

In [ ]:
import torch
tor = torch.rand([1, 4], device="cuda")
tor

tensor([[0.9546, 0.4950, 0.9420, 0.5926]], device='cuda:0')

### Exerciese

In [ ]:
# Exercises
import torch

random_tensor = torch.randn(7, 7)
random_tensor

tensor([[ 1.1935e+00,  1.7397e+00, -4.3484e-01, -8.5468e-02,  1.8322e-01,
          5.0642e-01,  1.9900e+00],
        [ 1.2483e+00,  1.2275e+00, -2.1167e-01, -8.8783e-01,  2.0494e-01,
          1.0686e+00,  2.8133e-01],
        [-1.5339e+00,  8.7219e-01,  5.5708e-01, -3.9735e-01, -9.1611e-01,
          9.2584e-01, -1.4433e-01],
        [-1.0785e+00, -1.7807e+00, -1.4240e+00,  2.9880e-02,  4.8121e-01,
         -8.7653e-01,  1.1603e+00],
        [ 1.5558e+00,  1.7620e-01, -2.4632e+00,  4.5076e-01,  1.2311e-02,
         -3.9611e-01,  8.9745e-01],
        [-3.0319e-01, -1.4598e+00, -9.5094e-01,  7.5371e-01,  6.0658e-01,
          1.8839e+00,  4.1715e-01],
        [-1.5307e+00, -3.4031e-01, -6.3550e-01,  4.8365e-01, -1.7753e-03,
          1.5861e-01, -9.2104e-01]])

In [ ]:
random_tensor2 = torch.randn(1, 7)

random_tensor2 = torch.transpose(random_tensor2, 1, 0)
random_tensor2.shape
torch.matmul(random_tensor, random_tensor2)

tensor([[-2.5413],
        [-1.3240],
        [-0.2698],
        [ 0.1093],
        [ 0.8469],
        [ 2.0342],
        [ 1.8008]])

In [ ]:
# Set manual seed
import torch
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(7, 1)
tensor2 = torch.transpose(tensor2, -2, 0)

# Matrix multiply tensors
torch.matmul(tensor1, tensor2), torch.matmul(tensor1, tensor2).shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
devicee = "cuda" if torch.cuda.is_available() else "cpu"


torch.cuda.manual_seed(1234)
tensor1 = torch.rand([2, 3], device=devicee)

torch.cuda.manual_seed(1234)
tensor2 = torch.rand([2, 3], device=devicee)

torch2 = torch.transpose(tensor2, -1, 0)
tensor1.shape, torch2.shape
output = torch.matmul(tensor1, torch2)
torch.matmul(tensor1, torch2).shape, output

(torch.Size([2, 2]),
 tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'))

In [ ]:
torch.max(output), torch.min(output)

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

In [ ]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_without = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(random_tensor_without, random_tensor_without.shape)

NameError: name 'torch' is not defined

In [ ]:
import torch

torch.cuda.manual_seed(42)